<?php
echo '<div class="container" id="container">';
	echo '<div class="row">';
		echo '<div class="col-md-12">';
			echo '<h2 id="education">Education</h2>';
			echo '<p>Samual V. Champion Highschool';
			echo '<br/>Boerne, TX';
			echo '<br/><i>Graduated with diploma June 2012</i></p>';
			echo '<p>University of Texas San Antonio';
			echo '<br/>San Antonio, TX';
			echo '<br/>GPA: 2.76';
			echo '<br/><i>Bachelor of Science (B.S.) Computer Science Candidate (Expected graduation May 2023)</i></p>';
		echo '</div>';
	echo '</div>';
	echo '<div class="row">';
		echo '<div class="col-md-12">';
			echo '<h2 align="center">Relavent Coursework</h2>';
			echo '<table border="1" align="center">';
				echo '<thead><tr><th>Course Number</th><th>Couse Name</th><th>Description</th><th>Relavent Subjects</th></tr></thead>';
				echo '<tr><td>CS 2123</td><td>Data Structures</td><td>Learn foundational data structures, how they work, and what situations they are optimal for.</td><td align="center">C</td></tr>';
				echo '<tr><td>IS 3513</td><td>Info Assurance and Security</td><td>Learn the fundamentals to encryption, how easy network traffic is intercepted and minimulated, and the overall importance of cyber security</td><td align="center">Metasploit, Wireshark, PGP</td></tr>';

				echo '<tr><td>MOT 4143</td><td>Intro to Project Management</td><td>Learn the fundamentals to project management and how they affect the out comes of projects and products for all stakeholders</td><td align="center">Project Management</td></tr>';
				echo '<tr><td>CS 3442</td><td>Applications Programming</td><td>Learn fundamentals to conventionally develope working software in a team setting.</td><td align="center">Java, Git</td></tr>';
				echo '<tr><td>CS 3424</td><td>Systems Programming</td><td>Learn script how to use a linux environment partnered with scripts to accomplish tasks.</td><td align="center">Linux Admin, Bash, Python, C</td></tr>';
				echo '<tr><td>CS 3844</td><td>Computer Organization</td><td>Learn how C breaks down into assembly and the basics of how logic circuits function</td><td align="center">ATT Assembly, C</td></tr>';
				echo '<tr><td>CS 3853</td><td >Computer Architecture</td><td>Learn more in depth how our code is broken down into machine language, and how out CPU processes this code.</td><td align="center">MIPS, C</td></tr>';
				echo '<tr><td>CS 4413</td><td>Web Technologies</td><td>Learn how web services are created and function, partnering a brief introduction to DevOps and Software Engineering</td><td align="center">DevOpds, HTML</td></tr>';
				echo '<tr><td>CS 3771</td><td>Software Engineering</td><td>Learn how project management interfaces with software developement to more efficiently manage projects and products in a team.</td><td align="center">Agile, Scrum</td></tr>';
				echo '<tr><td>CS 3723</td><td>Programming Languages</td><td>Look at programming manguages more indepth, and understand the nuances between the languages beyond simply syntax.</td><td align="center">C, Python, LISP</td></tr>';
			echo '</table>';
		echo '</div>';
	echo '</div>';
	echo '<div class="row">';
		echo '<div class="col-md-12">';
			echo '<h2 align="center">Previous Semester</h2>';
			echo '<table border="1" align="center">';
				echo '<thead><tr><th colspan="4" align="center">Course Schedule Fall 2021</th></tr></thead>';
				echo '<thead><tr><th>Couse Number</th><th>School</th><th>Course Name</th><th align="center">Course Style</th></tr></thead>';
				echo '<tr><td>MAT 1224</td><td>SAC</td><td>Calculus 2</td><td align="center">Online</td></tr>';
				echo '<tr><td>CS 3443</td><td>UTSA</td><td>Applications Programming</td><td align="center">Online</td></tr>';
				echo '<tr><td>CS 3853</td><td>UTSA</td><td>Computer Architecture</td><td align="center">Online</td></tr>';
			echo '</table>';
		echo '</div>';
	echo '</div>';
	echo '<div class="row">';
		echo '<div class="col-md-12">';
			echo '<h2 align="center">Current Semester</h2>';
			echo '<table border="1" align="center">';
				echo '<thead><tr><th colspan="6" align="center">Course Schedule Spring 2022</th></tr></thead>';
				echo '<thead><tr><th>Couse Number</th><th>Section</th><th>Course Name</th><th>Days of Week</th><th>Time</th><th>Room Number</th></tr></thead>';
				echo '<tr><td>CS 4413</td><td>001</td><td>Web Technologies</td><td align="center">M-W-F</td><td>10:00AM - 10:50AM</td><td align="center">NPB 1.202</td></tr>';
				echo '<tr><td>CS 3771</td><td>001</td><td>Software Engineering</td><td align="center">M-W-F</td><td>1:00AM - 1:50AM</td><td  align="center">MH 2.01.36</td></tr>';
				echo '<tr><td>CS 3723</td><td>003</td><td>Programming Languages</td><td align="center">T-R</td><td>8:30AM - 9:45AM</td><td  align="center">Online</td></tr>';
			echo '</table>';
		echo '</div>';
	echo '</div>';
echo '</div>';
?>